// GENERATED by scripts/select-audience.mjs. Do not edit by hand.
// Audience: NONE. No captured programme is compiled into this build.
//
// Regenerate one locally:
//   node integrations/vault/preview.mjs --root <vault> --file ... > manifest.json
//   node scripts/build-captured-program.mjs --manifest manifest.json --spec <spec>
//   node scripts/select-audience.mjs internal
import type { Program } from "../core.ts";

export const capturedProgram: Program | undefined = undefined;
