import { chromium, request } from '@playwright/test';
import assert from 'node:assert/strict';
const baseURL = process.env.MEMORY_TEST_URL || 'http://localhost:3024';
// This test identity header is for the loopback dev server only. Hosted identity comes from Sites.
if (!/^http:\/\/(localhost|127\.0\.0\.1):\d+$/.test(baseURL)) throw new Error('Local test only.');
const owner = 'memory-' + crypto.randomUUID() + '@example.invalid';
const api = await request.newContext({ baseURL, extraHTTPHeaders: { 'oai-authenticated-user-email': owner, Origin: baseURL } });
const other = await request.newContext({ baseURL, extraHTTPHeaders: { 'oai-authenticated-user-email': 'other-' + owner, Origin: baseURL } });
const anonymous = await request.newContext({ baseURL });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
try {
  assert.equal((await anonymous.get('/api/memory')).status(), 401);
  let data = await (await api.get('/api/memory')).json();
  assert.equal(data.revision, 0);
  const start = { id: crypto.randomUUID(), revision: 0, action: 'start', role: 'scientist' };
  let response = await api.post('/api/memory', { data: start });
  assert.equal(response.status(), 200, await response.text());
  data = await response.json();
  assert.equal(data.revision, 1);
  response = await api.post('/api/memory', { data: start });
  assert.equal((await response.json()).revision, 1, 'Retry must not duplicate');
  response = await api.post('/api/memory', { data: { ...start, id: crypto.randomUUID() } });
  assert.equal(response.status(), 409, 'Stale revision must fail');
  const accepted = { id: crypto.randomUUID(), revision: 1, action: 'review', role: 'reviewer', runId: start.id, outcome: 'accepted', rationale: 'Fixture review.' };
  assert.equal((await api.post('/api/memory', { data: { ...accepted, role: 'scientist' } })).status(), 403);
  assert.equal((await api.post('/api/memory', { data: { ...accepted, rationale: '' } })).status(), 400);
  assert.equal((await api.post('/api/memory', { data: accepted, headers: { Origin: 'https://unrelated.invalid' } })).status(), 403);
  const otherData = await (await other.get('/api/memory')).json();
  assert.equal(otherData.state.runs.length, 0, 'Owner records must not leak');
  assert.equal((await other.post('/api/memory', { data: { ...accepted, revision: 0 } })).status(), 404);
  const ctx = await browser.newContext({ viewport: { width: 1200, height: 750 }, extraHTTPHeaders: { 'oai-authenticated-user-email': owner } });
  const page = await ctx.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(baseURL + '/memory');
  await page.getByText('Saved revision 1', { exact: false }).waitFor();
  await page.getByRole('button', { name: 'Demo scientist' }).click();
  await page.getByLabel('Assessment rationale').fill('Keep uncertainty visible.');
  await page.getByRole('button', { name: 'Accept assessment', exact: true }).click();
  await page.getByText('Saved revision 2', { exact: false }).waitFor();
  data = await (await api.get('/api/memory')).json();
  assert.equal(data.state.knowledge.length, 0, 'Assessment acceptance cannot promote knowledge');
  await page.getByLabel('Rationale for inference update').fill('Carry the unresolved conflict forward.');
  await page.getByRole('button', { name: 'Approve inference update' }).click();
  await page.getByText('Saved revision 3', { exact: false }).waitFor();
  await page.getByLabel('Rationale for gap update').fill('Reject this proposed update for the continuity test.');
  await page.getByRole('button', { name: 'Reject gap update' }).click();
  await page.getByText('Saved revision 4', { exact: false }).waitFor();
  await page.reload();
  await page.getByText('Saved revision 4', { exact: false }).waitFor();
  await page.getByRole('button', { name: 'Prepare synthetic assessment' }).click();
  await page.getByText('Saved revision 5', { exact: false }).waitFor();
  await page.getByText('Approved knowledge included (1)', { exact: true }).waitFor();
  data = await (await api.get('/api/memory')).json();
  assert.equal(data.state.runs.length, 2);
  assert.equal(data.state.runs[0].context.approvedKnowledge.length, 0);
  assert.equal(data.state.runs[1].context.approvedKnowledge.length, 1);
  assert.equal(data.state.runs[1].updates.length, 1);
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'public/screenshot.jpeg', type: 'jpeg', quality: 90 });
  // A genuinely fresh browser context still reads the same persisted records.
  const fresh = await browser.newContext({ viewport: { width: 390, height: 844 }, extraHTTPHeaders: { 'oai-authenticated-user-email': owner } });
  const mobile = await fresh.newPage();
  await mobile.goto(baseURL + '/memory');
  await mobile.getByText('Saved revision 5', { exact: false }).waitFor();
  assert(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile overflow');
  await mobile.getByRole('button', { name: 'Knowledge', exact: true }).click();
  await mobile.getByRole('heading', { name: 'What the next run can use.' }).waitFor();
  await mobile.screenshot({ path: '/tmp/vivamed-memory-mobile.png', fullPage: true });
  assert.deepEqual(errors, []);
  // Two valid competing writes from the same revision: exactly one commits.
  const currentRun = data.state.runs.at(-1);
  const race = await Promise.all(['accepted', 'changes_requested'].map(outcome => api.post('/api/memory', { data: { ...accepted, id: crypto.randomUUID(), revision: 5, runId: currentRun.id, outcome } })));
  assert.deepEqual(race.map(r => r.status()).sort(), [200, 409]);
  console.log('PASS: persisted API/browser workflow, refresh + fresh session, individual promotion, frozen snapshots, owner isolation, missing identity, role/rationale checks, CSRF, idempotency, stale/racing writes and mobile layout.');
  console.log('Restart-check identity: ' + owner);
} finally {
  await browser.close(); await api.dispose(); await other.dispose(); await anonymous.dispose();
}
